[build]
  functions = "./"    # diz ao Netlify que as funções estão na raiz
  publish = "./"      # publica o index.html na raiz


  

[[redirects]]
  from = "/*"
  to = "/assistir1.html"
  status = 200
